// jsonl.mjs — the storage primitives every stage shares.
//
// JSONL is the substrate for one reason: it is append-only, mergeable,
// greppable, and corruption costs one line rather than one file. Whole-file
// rewrites are avoided everywhere except the two derived artifacts (concepts,
// gaps), which are regenerated by definition.
//
// `dumps` reproduces Python's `json.dumps(row, ensure_ascii=False)` separators
// so a store written by these scripts stays diff-comparable against one written
// by the original Python pipeline. That comparability is what makes the
// migration testable rather than asserted.

import fs from "node:fs";
import path from "node:path";

/**
 * A number that must serialise as a float even when its value is integral.
 *
 * JavaScript has one number type; Python has two, and `json.dumps` writes
 * `1.0` where `String(1)` gives `1`. A score field that lands exactly on 1.0
 * would otherwise read as a real divergence when diffed against a store the
 * Python pipeline produced.
 */
class PyFloat {
  constructor(v) {
    this.v = v;
  }
}

export function pyFloat(n) {
  return new PyFloat(n);
}

/** Serialise one row with Python's default separators (", " and ": "). */
export function dumps(value) {
  return ser(value);
}

function ser(v) {
  if (v === null || v === undefined) return "null";
  if (v instanceof PyFloat) {
    if (!Number.isFinite(v.v)) return "null";
    return Number.isInteger(v.v) ? v.v.toFixed(1) : String(v.v);
  }
  const t = typeof v;
  if (t === "number") return Number.isFinite(v) ? String(v) : "null";
  if (t === "boolean") return v ? "true" : "false";
  if (t === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(ser).join(", ") + "]";
  if (t === "object") {
    const parts = [];
    for (const [k, val] of Object.entries(v)) {
      if (val === undefined) continue;
      parts.push(JSON.stringify(k) + ": " + ser(val));
    }
    return "{" + parts.join(", ") + "}";
  }
  return "null";
}

/**
 * Read a JSONL file. A missing file is an empty list, not an error: a stage
 * that has not run yet is a normal state, and treating it as a crash would
 * make the pipeline unresumable from a partial store.
 *
 * An unparseable line is reported and skipped rather than aborting the read,
 * so one corrupt row cannot hide the other ten thousand.
 */
export function readJsonl(file) {
  if (!fs.existsSync(file)) return [];
  const out = [];
  const text = fs.readFileSync(file, "utf8");
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].trim();
    if (!raw) continue;
    try {
      out.push(JSON.parse(raw));
    } catch (e) {
      process.stderr.write(`WARN  ${file}:${i + 1} unparseable, skipped (${e.message})\n`);
    }
  }
  return out;
}

/** Read a JSONL file keeping each row's line number, for error reporting. */
export function readJsonlWithLines(file) {
  if (!fs.existsSync(file)) return [];
  const out = [];
  const lines = fs.readFileSync(file, "utf8").split("\n");
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].trim();
    if (!raw) continue;
    try {
      out.push({ row: JSON.parse(raw), line: i + 1 });
    } catch (e) {
      out.push({ row: null, line: i + 1, error: e.message });
    }
  }
  return out;
}

export function writeJsonl(file, rows) {
  fs.mkdirSync(path.dirname(file) || ".", { recursive: true });
  fs.writeFileSync(file, rows.map((r) => dumps(r) + "\n").join(""), "utf8");
}

/** Append rows without rewriting what is already there. */
export function appendJsonl(file, rows) {
  if (!rows.length) return;
  fs.mkdirSync(path.dirname(file) || ".", { recursive: true });
  fs.appendFileSync(file, rows.map((r) => dumps(r) + "\n").join(""), "utf8");
}

/** Every claim in the store, walked in sorted order so runs are reproducible. */
export function collectClaims(root) {
  const dir = path.join(root, "claims");
  const claims = [];
  walk(dir, (file) => {
    if (file.endsWith(".jsonl")) claims.push(...readJsonl(file));
  });
  return claims;
}

/** Every claim with the file and line it came from, for write-time rejection. */
export function collectClaimsLocated(root) {
  const dir = path.join(root, "claims");
  const out = [];
  walk(dir, (file) => {
    if (!file.endsWith(".jsonl")) return;
    for (const { row, line, error } of readJsonlWithLines(file)) {
      out.push({ claim: row, where: `${file}:${line}`, error });
    }
  });
  return out;
}

function walk(dir, fn) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, fn);
    else fn(full);
  }
}

/** ISO-8601 to the second, matching the Python pipeline's timestamp shape. */
export function nowIso() {
  return new Date().toISOString().replace(/\.\d{3}Z$/, "+00:00");
}

/** Parse `--flag value` and `--flag=value` into a plain object. */
export function parseArgs(argv, defaults = {}) {
  const out = { _: [], ...defaults };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) {
      out._.push(a);
      continue;
    }
    const eq = a.indexOf("=");
    if (eq !== -1) {
      out[a.slice(2, eq)] = a.slice(eq + 1);
    } else if (i + 1 < argv.length && !argv[i + 1].startsWith("--")) {
      out[a.slice(2)] = argv[++i];
    } else {
      out[a.slice(2)] = true;
    }
  }
  return out;
}
