#!/usr/bin/env node
// install-ci.mjs — the tier the author cannot switch off.
//
// Hooks are a courtesy: `--no-verify` turns them off, and a hooks directory is
// a per-machine setting nobody else can see. CI runs on a clean checkout where
// the person being checked has no vote, which is the only place a policy is
// enforced rather than encouraged.
//
// It writes the same `check-store.mjs` invocation the hooks run, so there is
// one implementation of every rule. Three enforcement points that disagree
// about the rules are three policies.
//
//   node install-ci.mjs                 # preview
//   node install-ci.mjs --apply
//   node install-ci.mjs --platform gitlab --apply
//
// Refuses when the skill is not committed to the repository, because CI has
// no other way to reach it.

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { parseArgs } from "./lib/jsonl.mjs";

const SKILL_REL = ".cline/skills/distilling-knowledge-into-skills";

const GITHUB = `# Generated by ${SKILL_REL}/scripts/install-ci.mjs
#
# The same checks the pre-commit hook runs, in the one place --no-verify cannot
# reach. A store that fails here is a store that would have shipped rules
# nobody can trace.
name: claim store

on:
  push:
  pull_request:

jobs:
  check-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Test suite
        run: node ${SKILL_REL}/tests/run-tests.mjs
      - name: Extractor conformance
        run: node ${SKILL_REL}/scripts/extractor-check.mjs --record
      - name: Skill contract
        # A skill that fails discovery has produced nothing, however good its
        # contents. Checked here for every compiled package, including this one.
        # CI is also where a real YAML parser is reliably available, so the
        # frontmatter is confirmed rather than pattern-matched.
        run: node ${SKILL_REL}/scripts/skill-lint.mjs
      - name: Cline hook contract, statically
        # This tier cannot be proven by running it — that needs a live Cline.
        # Checking the generated files against the documented contract is what
        # is available, and it is what caught the last four mistakes.
        run: node ${SKILL_REL}/scripts/hooks-lint.mjs --root .
      - name: Check the claim store, digests included
        # --verify re-reads every segment file, which is why it runs here and
        # not in the pre-commit hook: recording a digest and never checking it
        # is not provenance.
        run: node ${SKILL_REL}/scripts/check-store.mjs --root . --profile strict --verify
      - name: Certificate
        # Withheld rather than failed: a withheld certificate is a result. The
        # step reports it and does not stop the build, because incompleteness
        # is a measurement and not an error.
        run: node ${SKILL_REL}/scripts/certify.mjs --root . || true
`;

const GITLAB = `# Generated by ${SKILL_REL}/scripts/install-ci.mjs
check-store:
  image: node:20
  script:
    - node ${SKILL_REL}/tests/run-tests.mjs
    - node ${SKILL_REL}/scripts/extractor-check.mjs --record
    - node ${SKILL_REL}/scripts/skill-lint.mjs
    - node ${SKILL_REL}/scripts/hooks-lint.mjs --root .
    - node ${SKILL_REL}/scripts/check-store.mjs --root . --profile strict --verify
    - node ${SKILL_REL}/scripts/certify.mjs --root . || true
`;

function main() {
  const args = parseArgs(process.argv.slice(2), { root: ".", platform: "github" });
  const apply = Boolean(args.apply);

  const script = path.join(args.root, SKILL_REL, "scripts", "check-store.mjs");
  if (!fs.existsSync(script)) {
    process.stderr.write(
      `BLOCKED: ${SKILL_REL}/ is not in this repository.\n` +
        `CI runs on a clean checkout, so the checks must be committed here rather\n` +
        `than installed on one machine.\n`
    );
    process.exit(2);
  }

  let tracked = false;
  try {
    execSync(`git ls-files --error-unmatch "${SKILL_REL}/scripts/check-store.mjs"`, {
      cwd: args.root,
      stdio: "ignore",
    });
    tracked = true;
  } catch {
    /* not tracked yet */
  }
  if (!tracked) {
    process.stderr.write(
      `WARNING: ${SKILL_REL}/scripts/check-store.mjs is not tracked by git yet.\n` +
        `The pipeline will fail on a clean checkout until it is committed.\n\n`
    );
  }

  const [file, body] =
    args.platform === "gitlab"
      ? [path.join(args.root, ".gitlab", "ci", "claim-store.yml"), GITLAB]
      : [path.join(args.root, ".github", "workflows", "claim-store.yml"), GITHUB];

  process.stdout.write(`${apply ? "write" : "would write"}  ${file}\n`);
  if (apply) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body, "utf8");
  } else {
    process.stdout.write("\nNothing was written. Pass --apply to act.\n");
  }
}

main();
